name: Actualizar lista

on:
  schedule:
    - cron: '0 12 * * *'  # Todos los días a las 12:00 UTC
    - cron: '0 15 * * *'  # Todos los días a las 15:00 UTC
    - cron: '0 17 * * *'  # Todos los días a las 17:00 UTC
    - cron: '0 19 * * *'  # Todos los dias a las 19:00 UTC
  workflow_dispatch:      # Permite ejecutarlo manualmente

permissions:
  contents: write

jobs:
  descarga_reemplazo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
       
      - name: Descargar archivo original
        run: |
          curl -L -f "https://ipfs.io/ipns/k2k4r8oqlcjxsritt5mczkcn4mmvcmymbqw7113fz2flkrerfwfps004/data/listas/lista_iptv.m3u" -o lista_original.m3u
          if [ ! -s lista_original.m3u ]; then
            echo "Error: El archivo descargado está vacío"
            exit 1
          fi
       
      - name: Reemplazar IP y puerto
        run: sed 's/127.0.0.1:6878/192.168.0.9:6878/g' lista_original.m3u > ch_lan.m3u
       
      - name: Verificar si hay cambios
        id: verify_diff
        run: |
          git add ch_lan.m3u
          if git diff --staged --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
       
      - name: Commit y push de la lista modificada
        if: steps.verify_diff.outputs.changed == 'true'
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -m "Actualización automática: lista IPTV con nueva IP y puerto"
          git push
